import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/layout/navbar/page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body>
        <div className="xl:w-[1200px] mx-auto">
          <Navbar />
        {children}
        </div>
      </body>
    </html>
  );
}
